// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Microsoft.Marketplace.Storefront
{

    public partial class Product
    {
        public class AlternateId2
        {

            [JsonProperty("$type")]
            public string Type { get; set; }

            [JsonProperty("AlternateIdType")]
            public string AlternateIdType { get; set; }

            [JsonProperty("AlternateIdValue")]
            public string AlternateIdValue { get; set; }

            [JsonProperty("AlternatedIdTypeString")]
            public string AlternatedIdTypeString { get; set; }
        }
    }

}
