// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace Microsoft.Marketplace.Storefront
{

    public partial class Product
    {

        [JsonProperty("$type")]
        public string Type { get; set; }

        [JsonProperty("Path")]
        public string Path { get; set; }

        [JsonProperty("ExpiryUtc")]
        public string ExpiryUtc { get; set; }

        [JsonProperty("Payload")]
        public Payload2 Payload { get; set; }
    }

}
