// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Microsoft.Marketplace.Storefront
{

    public partial class Product
    {
        public class SupportUri
        {

            [JsonProperty("$type")]
            public string Type { get; set; }

            [JsonProperty("Uri")]
            public string Uri { get; set; }

            [JsonProperty("Purpose")]
            public object Purpose { get; set; }
        }
    }

}
