// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Microsoft.Marketplace.Storefront
{

    public partial class Product
    {
        public class Item
        {

            [JsonProperty("$type")]
            public string Type { get; set; }

            [JsonProperty("Level")]
            public string Level { get; set; }

            [JsonProperty("ItemCode")]
            public string ItemCode { get; set; }

            [JsonProperty("Name")]
            public string Name { get; set; }

            [JsonProperty("Description")]
            public string Description { get; set; }

            [JsonProperty("ValidationHint")]
            public string ValidationHint { get; set; }

            [JsonProperty("IsValidationPassed")]
            public bool? IsValidationPassed { get; set; }

            [JsonProperty("HelpLink")]
            public string HelpLink { get; set; }

            [JsonProperty("HelpTitle")]
            public string HelpTitle { get; set; }
        }
    }

}
