// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Microsoft.Marketplace.Storefront
{

    public partial class Product
    {
        public class Trailer
        {

            [JsonProperty("$type")]
            public string Type { get; set; }

            [JsonProperty("Title")]
            public string Title { get; set; }

            [JsonProperty("VideoPurpose")]
            public string VideoPurpose { get; set; }

            [JsonProperty("Url")]
            public string Url { get; set; }

            [JsonProperty("AudioEncoding")]
            public string AudioEncoding { get; set; }

            [JsonProperty("VideoEncoding")]
            public string VideoEncoding { get; set; }

            [JsonProperty("DeepLink")]
            public object DeepLink { get; set; }

            [JsonProperty("Image")]
            public Image3 Image { get; set; }

            [JsonProperty("Bitrate")]
            public int Bitrate { get; set; }

            [JsonProperty("Width")]
            public int Width { get; set; }

            [JsonProperty("Height")]
            public int Height { get; set; }

            [JsonProperty("VideoPositionInfo")]
            public string VideoPositionInfo { get; set; }
        }
    }

}
