// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Microsoft.Marketplace.Storefront
{

    public partial class Product
    {
        public class Availability
        {

            [JsonProperty("$type")]
            public string Type { get; set; }

            [JsonProperty("AvailabilityId")]
            public string AvailabilityId { get; set; }

            [JsonProperty("Price")]
            public double Price { get; set; }

            [JsonProperty("DisplayPrice")]
            public string DisplayPrice { get; set; }

            [JsonProperty("StrikethroughPrice")]
            public string StrikethroughPrice { get; set; }

            [JsonProperty("PromoMessage")]
            public string PromoMessage { get; set; }

            [JsonProperty("Remediations")]
            public object Remediations { get; set; }

            [JsonProperty("RemediationRequired")]
            public bool RemediationRequired { get; set; }

            [JsonProperty("AvailabilityEndDate")]
            public string AvailabilityEndDate { get; set; }

            [JsonProperty("PreorderReleaseDate")]
            public string PreorderReleaseDate { get; set; }

            [JsonProperty("DisplayRank")]
            public int DisplayRank { get; set; }

            [JsonProperty("DisplayGroup")]
            public object DisplayGroup { get; set; }

            [JsonProperty("Affirmation")]
            public object Affirmation { get; set; }

            [JsonProperty("Conditions")]
            public Conditions2 Conditions { get; set; }

            [JsonProperty("Actions")]
            public string[] Actions { get; set; }
        }
    }

}
