// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Microsoft.Marketplace.Storefront
{

    public partial class Product
    {
        public class ProductRating
        {

            [JsonProperty("$type")]
            public string Type { get; set; }

            [JsonProperty("RatingSystem")]
            public string RatingSystem { get; set; }

            [JsonProperty("RatingSystemId")]
            public string RatingSystemId { get; set; }

            [JsonProperty("RatingSystemUrl")]
            public string RatingSystemUrl { get; set; }

            [JsonProperty("RatingValue")]
            public string RatingValue { get; set; }

            [JsonProperty("RatingId")]
            public string RatingId { get; set; }

            [JsonProperty("RatingValueLogoUrl")]
            public string RatingValueLogoUrl { get; set; }

            [JsonProperty("RatingAge")]
            public int RatingAge { get; set; }

            [JsonProperty("RestrictMetadata")]
            public bool RestrictMetadata { get; set; }

            [JsonProperty("RestrictPurchase")]
            public bool RestrictPurchase { get; set; }

            [JsonProperty("RatingDescriptors")]
            public string[] RatingDescriptors { get; set; }

            [JsonProperty("RatingDescriptorLogoUrls")]
            public object[] RatingDescriptorLogoUrls { get; set; }

            [JsonProperty("RatingDisclaimers")]
            public object[] RatingDisclaimers { get; set; }

            [JsonProperty("InteractiveElements")]
            public string[] InteractiveElements { get; set; }

            [JsonProperty("LongName")]
            public string LongName { get; set; }

            [JsonProperty("ShortName")]
            public string ShortName { get; set; }

            [JsonProperty("Description")]
            public string Description { get; set; }
        }
    }

}
