// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Microsoft.Marketplace.Storefront
{

    public partial class Product
    {
        public class SkuDisplayRank
        {

            [JsonProperty("$type")]
            public string Type { get; set; }

            [JsonProperty("Dimension")]
            public object Dimension { get; set; }

            [JsonProperty("Rank")]
            public int Rank { get; set; }
        }
    }

}
