// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Microsoft.Marketplace.Storefront
{

    public partial class Product
    {
        public class Minimum2
        {

            [JsonProperty("$type")]
            public string Type { get; set; }

            [JsonProperty("Title")]
            public string Title { get; set; }

            [JsonProperty("Items")]
            public Item[] Items { get; set; }

            [JsonProperty("EmptySectionMessage")]
            public string EmptySectionMessage { get; set; }
        }
    }

}
