// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Microsoft.Marketplace.Storefront
{

    public partial class Product
    {
        public class SystemRequirements2
        {

            [JsonProperty("Minimum")]
            public Minimum2 Minimum { get; set; }

            [JsonProperty("Recommended")]
            public Recommended2 Recommended { get; set; }
        }
    }

}
