// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Microsoft.Marketplace.Storefront
{

    public partial class Product
    {
        public class Image3
        {

            [JsonProperty("$type")]
            public string Type { get; set; }

            [JsonProperty("ImageType")]
            public string ImageType { get; set; }

            [JsonProperty("Url")]
            public string Url { get; set; }

            [JsonProperty("Height")]
            public int Height { get; set; }

            [JsonProperty("Width")]
            public int Width { get; set; }

            [JsonProperty("BackgroundColor")]
            public string BackgroundColor { get; set; }

            [JsonProperty("ForegroundColor")]
            public string ForegroundColor { get; set; }

            [JsonProperty("Caption")]
            public string Caption { get; set; }

            [JsonProperty("ImagePositionInfo")]
            public string ImagePositionInfo { get; set; }
        }
    }

}
