// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Microsoft.Marketplace.Storefront
{

    public partial class Product
    {
        public class Sku
        {

            [JsonProperty("$type")]
            public string Type { get; set; }

            [JsonProperty("SkuId")]
            public string SkuId { get; set; }

            [JsonProperty("Actions")]
            public string[] Actions { get; set; }

            [JsonProperty("AvailabilityId")]
            public string AvailabilityId { get; set; }

            [JsonProperty("SkuType")]
            public string SkuType { get; set; }

            [JsonProperty("Price")]
            public double Price { get; set; }

            [JsonProperty("DisplayPrice")]
            public string DisplayPrice { get; set; }

            [JsonProperty("StrikethroughPrice")]
            public string StrikethroughPrice { get; set; }

            [JsonProperty("PromoMessage")]
            public string PromoMessage { get; set; }

            [JsonProperty("PromoEndDateUtc")]
            public string PromoEndDateUtc { get; set; }

            [JsonProperty("CurrencyCode")]
            public string CurrencyCode { get; set; }

            [JsonProperty("CurrencySymbol")]
            public string CurrencySymbol { get; set; }

            [JsonProperty("ResourceSetId")]
            public string ResourceSetId { get; set; }

            [JsonProperty("IsPaymentInstrumentRequired")]
            public bool IsPaymentInstrumentRequired { get; set; }

            [JsonProperty("FulfillmentData")]
            public string FulfillmentData { get; set; }

            [JsonProperty("MSAPurchaseType")]
            public string MSAPurchaseType { get; set; }

            [JsonProperty("PackageRequirements")]
            public PackageRequirement[] PackageRequirements { get; set; }

            [JsonProperty("TimedTrialMessage")]
            public string TimedTrialMessage { get; set; }

            [JsonProperty("RemainingDaysInTrial")]
            public int RemainingDaysInTrial { get; set; }

            [JsonProperty("DurationInSeconds")]
            public int? DurationInSeconds { get; set; }

            [JsonProperty("HardwareRequirements")]
            public string[] HardwareRequirements { get; set; }

            [JsonProperty("HardwareWarnings")]
            public string[] HardwareWarnings { get; set; }

            [JsonProperty("OperatingSystemType")]
            public object OperatingSystemType { get; set; }

            [JsonProperty("Images")]
            public object Images { get; set; }

            [JsonProperty("StartDate")]
            public string StartDate { get; set; }

            [JsonProperty("EndDate")]
            public string EndDate { get; set; }

            [JsonProperty("RequiredEntitlementKeys")]
            public object RequiredEntitlementKeys { get; set; }

            [JsonProperty("ContentIds")]
            public object ContentIds { get; set; }

            [JsonProperty("UpgradeToProductId")]
            public object UpgradeToProductId { get; set; }

            [JsonProperty("SkuTitle")]
            public string SkuTitle { get; set; }

            [JsonProperty("SkuButtonTitle")]
            public string SkuButtonTitle { get; set; }

            [JsonProperty("SkuDisplayRanks")]
            public SkuDisplayRank[] SkuDisplayRanks { get; set; }

            [JsonProperty("RecurrencePolicyId")]
            public string RecurrencePolicyId { get; set; }

            [JsonProperty("RecurrencePolicyTitle")]
            public string RecurrencePolicyTitle { get; set; }

            [JsonProperty("ConsumableQuantity")]
            public object ConsumableQuantity { get; set; }

            [JsonProperty("Availabilities")]
            public Availability[] Availabilities { get; set; }

            [JsonProperty("BundledSkus")]
            public string[] BundledSkus { get; set; }

            [JsonProperty("IsPreorder")]
            public bool IsPreorder { get; set; }

            [JsonProperty("FirstAvailableDate")]
            public string FirstAvailableDate { get; set; }

            [JsonProperty("IsRepurchasable")]
            public bool IsRepurchasable { get; set; }

            [JsonProperty("Description")]
            public string Description { get; set; }

            [JsonProperty("SkuInformationChart")]
            public object SkuInformationChart { get; set; }
        }
    }

}
