// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Microsoft.Marketplace.Storefront
{

    public partial class Product
    {
        public class Conditions2
        {

            [JsonProperty("$type")]
            public string Type { get; set; }

            [JsonProperty("EndDate")]
            public string EndDate { get; set; }

            [JsonProperty("StartDate")]
            public string StartDate { get; set; }

            [JsonProperty("ResourceSetIds")]
            public string[] ResourceSetIds { get; set; }

            [JsonProperty("ClientConditions")]
            public ClientConditions2 ClientConditions { get; set; }
        }
    }

}
