// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Microsoft.Marketplace.Storefront
{

    public partial class Product
    {
        public class PlatformDependency
        {

            [JsonProperty("$type")]
            public string Type { get; set; }

            [JsonProperty("PlatformName")]
            public string PlatformName { get; set; }

            [JsonProperty("MinVersion")]
            public object MinVersion { get; set; }

            [JsonProperty("MaxTested")]
            public object MaxTested { get; set; }
        }
    }

}
