// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Microsoft.Marketplace.Storefront
{

    public partial class Product
    {
        public class AppExtension2
        {

            [JsonProperty("$type")]
            public string Type { get; set; }

            [JsonProperty("AppWithExt")]
            public bool AppWithExt { get; set; }

            [JsonProperty("AppExtCategoryNames")]
            public string[] AppExtCategoryNames { get; set; }

            [JsonProperty("LocalizedCategoryNames")]
            public object[] LocalizedCategoryNames { get; set; }

            [JsonProperty("AppExtTypes")]
            public string[] AppExtTypes { get; set; }

            [JsonProperty("AppExtTypeStrings")]
            public string[] AppExtTypeStrings { get; set; }

            [JsonProperty("AppExtCapabilities")]
            public object AppExtCapabilities { get; set; }
        }
    }

}
