// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Microsoft.Marketplace.Storefront
{

    public partial class Product
    {
        public class Payload2
        {

            [JsonProperty("$type")]
            public string Type { get; set; }

            [JsonProperty("Platforms")]
            public string[] Platforms { get; set; }

            [JsonProperty("PrivacyUrl")]
            public string PrivacyUrl { get; set; }

            [JsonProperty("LegalUrl")]
            public object LegalUrl { get; set; }

            [JsonProperty("Accessible")]
            public bool Accessible { get; set; }

            [JsonProperty("IsDeviceCompanionApp")]
            public bool IsDeviceCompanionApp { get; set; }

            [JsonProperty("SupportUris")]
            public SupportUri[] SupportUris { get; set; }

            [JsonProperty("Features")]
            public string[] Features { get; set; }

            [JsonProperty("Notes")]
            public string[] Notes { get; set; }

            [JsonProperty("SupportedLanguages")]
            public string[] SupportedLanguages { get; set; }

            [JsonProperty("PublisherCopyrightInformation")]
            public string PublisherCopyrightInformation { get; set; }

            [JsonProperty("AdditionalLicenseTerms")]
            public string AdditionalLicenseTerms { get; set; }

            [JsonProperty("ApproximateSizeInBytes")]
            public object ApproximateSizeInBytes { get; set; }

            [JsonProperty("MaxInstallSizeInBytes")]
            public long? MaxInstallSizeInBytes { get; set; }

            [JsonProperty("AppWebsiteUrl")]
            public string AppWebsiteUrl { get; set; }

            [JsonProperty("ProductRatings")]
            public ProductRating[] ProductRatings { get; set; }

            [JsonProperty("RequiredHardware")]
            public object RequiredHardware { get; set; }

            [JsonProperty("RecommendedHardware")]
            public object RecommendedHardware { get; set; }

            [JsonProperty("HardwareWarnings")]
            public object HardwareWarnings { get; set; }

            [JsonProperty("PermissionsRequired")]
            public string[] PermissionsRequired { get; set; }

            [JsonProperty("PackageAndDeviceCapabilities")]
            public string[] PackageAndDeviceCapabilities { get; set; }

            [JsonProperty("Version")]
            public string Version { get; set; }

            [JsonProperty("LastUpdateDateUtc")]
            public string LastUpdateDateUtc { get; set; }

            [JsonProperty("Skus")]
            public Sku[] Skus { get; set; }

            [JsonProperty("OSProductInformation")]
            public object OSProductInformation { get; set; }

            [JsonProperty("CategoryId")]
            public string CategoryId { get; set; }

            [JsonProperty("SubcategoryId")]
            public string SubcategoryId { get; set; }

            [JsonProperty("NavItemId")]
            public string NavItemId { get; set; }

            [JsonProperty("AddOnPriceRange")]
            public string AddOnPriceRange { get; set; }

            [JsonProperty("RecurrencePolicy")]
            public string RecurrencePolicy { get; set; }

            [JsonProperty("DeviceFamilyDisallowedReason")]
            public string DeviceFamilyDisallowedReason { get; set; }

            [JsonProperty("BuiltFor")]
            public string BuiltFor { get; set; }

            [JsonProperty("Trailers")]
            public Trailer[] Trailers { get; set; }

            [JsonProperty("RevisionId")]
            public string RevisionId { get; set; }

            [JsonProperty("PdpBackgroundColor")]
            public string PdpBackgroundColor { get; set; }

            [JsonProperty("AppExtension")]
            public AppExtension2 AppExtension { get; set; }

            [JsonProperty("ContainsDownloadPackage")]
            public bool ContainsDownloadPackage { get; set; }

            [JsonProperty("SystemRequirements")]
            public SystemRequirements2 SystemRequirements { get; set; }

            [JsonProperty("KeyIds")]
            public string[] KeyIds { get; set; }

            [JsonProperty("AllowedPlatforms")]
            public string[] AllowedPlatforms { get; set; }

            [JsonProperty("Xbox360ContentMediaId")]
            public object Xbox360ContentMediaId { get; set; }

            [JsonProperty("EarlyAdopterEnrollmentUrl")]
            public object EarlyAdopterEnrollmentUrl { get; set; }

            [JsonProperty("InstallationTerms")]
            public string InstallationTerms { get; set; }

            [JsonProperty("SkuDisplayGroups")]
            public string[] SkuDisplayGroups { get; set; }

            [JsonProperty("XboxXpa")]
            public bool XboxXpa { get; set; }

            [JsonProperty("RelatedPackageIdentities")]
            public object RelatedPackageIdentities { get; set; }

            [JsonProperty("DetailsDisplayConfiguration")]
            public object DetailsDisplayConfiguration { get; set; }

            [JsonProperty("Categories")]
            public string[] Categories { get; set; }

            [JsonProperty("Images")]
            public Image3[] Images { get; set; }

            [JsonProperty("ProductId")]
            public string ProductId { get; set; }

            [JsonProperty("Title")]
            public string Title { get; set; }

            [JsonProperty("Subtitle")]
            public object Subtitle { get; set; }

            [JsonProperty("Description")]
            public string Description { get; set; }

            [JsonProperty("DeveloperName")]
            public string DeveloperName { get; set; }

            [JsonProperty("PublisherName")]
            public string PublisherName { get; set; }

            [JsonProperty("PublisherId")]
            public string PublisherId { get; set; }

            [JsonProperty("IsUniversal")]
            public bool IsUniversal { get; set; }

            [JsonProperty("Language")]
            public string Language { get; set; }

            [JsonProperty("BGColor")]
            public object BGColor { get; set; }

            [JsonProperty("FGColor")]
            public object FGColor { get; set; }

            [JsonProperty("Price")]
            public double Price { get; set; }

            [JsonProperty("DisplayPrice")]
            public string DisplayPrice { get; set; }

            [JsonProperty("StrikethroughPrice")]
            public string StrikethroughPrice { get; set; }

            [JsonProperty("PromoMessage")]
            public string PromoMessage { get; set; }

            [JsonProperty("PromoEndDateUtc")]
            public string PromoEndDateUtc { get; set; }

            [JsonProperty("AverageRating")]
            public double AverageRating { get; set; }

            [JsonProperty("RatingCount")]
            public int RatingCount { get; set; }

            [JsonProperty("HasFreeTrial")]
            public bool HasFreeTrial { get; set; }

            [JsonProperty("ProductType")]
            public string ProductType { get; set; }

            [JsonProperty("ProductFamilyName")]
            public string ProductFamilyName { get; set; }

            [JsonProperty("MediaType")]
            public string MediaType { get; set; }

            [JsonProperty("ContentIds")]
            public string[] ContentIds { get; set; }

            [JsonProperty("PackageFamilyNames")]
            public string[] PackageFamilyNames { get; set; }

            [JsonProperty("RecommendationReason")]
            public object RecommendationReason { get; set; }

            [JsonProperty("ReleaseNotes")]
            public object ReleaseNotes { get; set; }

            [JsonProperty("SubcategoryName")]
            public string SubcategoryName { get; set; }

            [JsonProperty("AlternateId")]
            public object AlternateId { get; set; }

            [JsonProperty("AlternateIds")]
            public AlternateId2[] AlternateIds { get; set; }

            [JsonProperty("CuratedBGColor")]
            public object CuratedBGColor { get; set; }

            [JsonProperty("CuratedFGColor")]
            public object CuratedFGColor { get; set; }

            [JsonProperty("CuratedImageUrl")]
            public object CuratedImageUrl { get; set; }

            [JsonProperty("CuratedTitle")]
            public object CuratedTitle { get; set; }

            [JsonProperty("CuratedDescription")]
            public object CuratedDescription { get; set; }

            [JsonProperty("DoNotFilter")]
            public object DoNotFilter { get; set; }

            [JsonProperty("CollectionItemType")]
            public string CollectionItemType { get; set; }

            [JsonProperty("CuratedVideoUri")]
            public object CuratedVideoUri { get; set; }

            [JsonProperty("ArtistName")]
            public object ArtistName { get; set; }

            [JsonProperty("ArtistId")]
            public object ArtistId { get; set; }

            [JsonProperty("AlbumTitle")]
            public object AlbumTitle { get; set; }

            [JsonProperty("AlbumProductId")]
            public object AlbumProductId { get; set; }

            [JsonProperty("IsExplicit")]
            public object IsExplicit { get; set; }

            [JsonProperty("NumberOfSeasons")]
            public int NumberOfSeasons { get; set; }

            [JsonProperty("ReleaseDateUtc")]
            public string ReleaseDateUtc { get; set; }

            [JsonProperty("DurationInSeconds")]
            public int DurationInSeconds { get; set; }

            [JsonProperty("IsCompatible")]
            public bool IsCompatible { get; set; }

            [JsonProperty("IsSoftBlocked")]
            public bool? IsSoftBlocked { get; set; }

            [JsonProperty("IncompatibleReason")]
            public string IncompatibleReason { get; set; }

            [JsonProperty("DeveloperOptOutOfSDCardInstall")]
            public bool DeveloperOptOutOfSDCardInstall { get; set; }

            [JsonProperty("HasAddOns")]
            public bool HasAddOns { get; set; }

            [JsonProperty("HasThirdPartyIAPs")]
            public bool HasThirdPartyIAPs { get; set; }

            [JsonProperty("ExternalUri")]
            public object ExternalUri { get; set; }

            [JsonProperty("AutosuggestSubtitle")]
            public object AutosuggestSubtitle { get; set; }

            [JsonProperty("MerchandizedProductType")]
            public object MerchandizedProductType { get; set; }

            [JsonProperty("VoiceTitle")]
            public string VoiceTitle { get; set; }

            [JsonProperty("PhraseCustomPronunciation")]
            public object PhraseCustomPronunciation { get; set; }

            [JsonProperty("PlaintextPassName")]
            public object PlaintextPassName { get; set; }

            [JsonProperty("GlyphTextPassName")]
            public object GlyphTextPassName { get; set; }

            [JsonProperty("SubscriptionDiscountMessageTemplate")]
            public object SubscriptionDiscountMessageTemplate { get; set; }

            [JsonProperty("Capabilities")]
            public string[] Capabilities { get; set; }

            [JsonProperty("HideFromCollections")]
            public bool HideFromCollections { get; set; }

            [JsonProperty("IsDownloadable")]
            public bool IsDownloadable { get; set; }

            [JsonProperty("HideFromDownloadsAndUpdates")]
            public bool HideFromDownloadsAndUpdates { get; set; }

            [JsonProperty("IncompatibleLink")]
            public object IncompatibleLink { get; set; }

            [JsonProperty("IncompatibleLabel")]
            public object IncompatibleLabel { get; set; }

            [JsonProperty("GamingOptionsXboxLive")]
            public bool GamingOptionsXboxLive { get; set; }

            [JsonProperty("ActionOverrides")]
            public object ActionOverrides { get; set; }

            [JsonProperty("AvailableDevicesDisplayText")]
            public string AvailableDevicesDisplayText { get; set; }

            [JsonProperty("AvailableDevicesNarratorText")]
            public string AvailableDevicesNarratorText { get; set; }
        }
    }

}
