// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Microsoft.Marketplace.Storefront
{

    public partial class Product
    {
        public class PackageRequirement
        {

            [JsonProperty("$type")]
            public string Type { get; set; }

            [JsonProperty("HardwareRequirements")]
            public string[] HardwareRequirements { get; set; }

            [JsonProperty("HardwareDependencies")]
            public string[] HardwareDependencies { get; set; }

            [JsonProperty("SupportedArchitectures")]
            public string[] SupportedArchitectures { get; set; }

            [JsonProperty("PlatformDependencies")]
            public PlatformDependency[] PlatformDependencies { get; set; }
        }
    }

}
