// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class AlternateId2
    {

        [JsonProperty("IdType")]
        public string IdType { get; set; }

        [JsonProperty("Value")]
        public string Value { get; set; }
    }

}
