// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class Application2
    {

        [JsonProperty("DeclarationOrder")]
        public int? DeclarationOrder { get; set; }

        [JsonProperty("Extensions")]
        public IList<string> Extensions { get; set; }

        [JsonProperty("ApplicationId")]
        public string ApplicationId { get; set; }
    }

}
