// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class Attribute
    {

        [JsonProperty("Name")]
        public string Name { get; set; }

        [JsonProperty("Minimum")]
        public int? Minimum { get; set; }

        [JsonProperty("Maximum")]
        public int? Maximum { get; set; }

        [JsonProperty("ApplicablePlatforms")]
        public object ApplicablePlatforms { get; set; }
    }

}
