// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class Availability
    {

        [JsonProperty("Properties")]
        public Properties3 Properties { get; set; }

        [JsonProperty("Conditions")]
        public Conditions Conditions { get; set; }

        [JsonProperty("AvailabilityASchema")]
        public string AvailabilityASchema { get; set; }

        [JsonProperty("AvailabilityBSchema")]
        public string AvailabilityBSchema { get; set; }

        [JsonProperty("AvailabilityId")]
        public string AvailabilityId { get; set; }

        [JsonProperty("LastModifiedDate")]
        public DateTime? LastModifiedDate { get; set; }

        [JsonProperty("Actions")]
        public IList<string> Actions { get; set; }

        [JsonProperty("SkuId")]
        public string SkuId { get; set; }

        [JsonProperty("OrderManagementData")]
        public OrderManagementData OrderManagementData { get; set; }

        [JsonProperty("Markets")]
        public IList<string> Markets { get; set; }

        [JsonProperty("DisplayRank")]
        public int? DisplayRank { get; set; }

        [JsonProperty("RemediationRequired")]
        public bool? RemediationRequired { get; set; }

        [JsonProperty("Remediations")]
        public IList<Remediation> Remediations { get; set; }

        [JsonProperty("AlternateIds")]
        public IList<AlternateId2> AlternateIds { get; set; }
    }

}
