// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class ClientConditions
    {

        [JsonProperty("DeviceTags")]
        public IList<object> DeviceTags { get; set; }

        [JsonProperty("AllowedPlatforms")]
        public IList<AllowedPlatform> AllowedPlatforms { get; set; }

        [JsonProperty("AllowedDevices")]
        public IList<object> AllowedDevices { get; set; }
    }

}
