// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class ContentRating
    {

        [JsonProperty("RatingSystem")]
        public string RatingSystem { get; set; }

        [JsonProperty("RatingDisclaimers")]
        public IList<object> RatingDisclaimers { get; set; }

        [JsonProperty("RatingDescriptors")]
        public IList<string> RatingDescriptors { get; set; }

        [JsonProperty("RatingId")]
        public string RatingId { get; set; }

        [JsonProperty("InteractiveElements")]
        public IList<string> InteractiveElements { get; set; }
    }

}
