// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class Delivery
    {

        [JsonProperty("Packages")]
        public IList<Package2> Packages { get; set; }

        [JsonProperty("FulfillmentDataList")]
        public IList<FulfillmentDataList> FulfillmentDataList { get; set; }
    }

}
