// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class DisplaySkuAvailability
    {

        [JsonProperty("Sku")]
        public Sku Sku { get; set; }

        [JsonProperty("Availabilities")]
        public IList<Availability> Availabilities { get; set; }
    }

}
