// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class DisplayPlatformProperty
    {

        [JsonProperty("PlatformName")]
        public string PlatformName { get; set; }

        [JsonProperty("TitleOverride")]
        public string TitleOverride { get; set; }

        [JsonProperty("DescriptionOverride")]
        public string DescriptionOverride { get; set; }
    }

}
