// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class FlightDetail
    {

        [JsonProperty("WuBundleId")]
        public string WuBundleId { get; set; }

        [JsonProperty("ReleaseRank")]
        public int? ReleaseRank { get; set; }

        [JsonProperty("GroupIds")]
        public IList<string> GroupIds { get; set; }

        [JsonProperty("ContentList")]
        public IList<ContentList> ContentList { get; set; }

        [JsonProperty("FlightId")]
        public string FlightId { get; set; }
    }

}
