// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class FrameworkDependency
    {

        [JsonProperty("PackageIdentity")]
        public string PackageIdentity { get; set; }

        [JsonProperty("MinVersion")]
        public long? MinVersion { get; set; }

        [JsonProperty("MaxTested")]
        public int? MaxTested { get; set; }
    }

}
