// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class FulfillmentData
    {

        [JsonProperty("WuCategoryId")]
        public string WuCategoryId { get; set; }

        [JsonProperty("WuBundleId")]
        public string WuBundleId { get; set; }

        [JsonProperty("Content")]
        public IList<Content> Content { get; set; }

        [JsonProperty("ReleaseRank")]
        public int? ReleaseRank { get; set; }

        [JsonProperty("ProductId")]
        public string ProductId { get; set; }

        [JsonProperty("SkuId")]
        public string SkuId { get; set; }

        [JsonProperty("PackageFamilyName")]
        public string PackageFamilyName { get; set; }

        [JsonProperty("LicensingPolicy")]
        public string LicensingPolicy { get; set; }

        [JsonProperty("PackagesShouldBePublishedToWu")]
        public bool? PackagesShouldBePublishedToWu { get; set; }
    }

}
