// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class HardwareProperties
    {

        [JsonProperty("MinimumHardware")]
        public IList<string> MinimumHardware { get; set; }

        [JsonProperty("RecommendedHardware")]
        public IList<string> RecommendedHardware { get; set; }

        [JsonProperty("MinimumProcessor")]
        public string MinimumProcessor { get; set; }

        [JsonProperty("RecommendedProcessor")]
        public string RecommendedProcessor { get; set; }

        [JsonProperty("MinimumGraphics")]
        public string MinimumGraphics { get; set; }

        [JsonProperty("RecommendedGraphics")]
        public string RecommendedGraphics { get; set; }
    }

}
