// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class Image
    {

        [JsonProperty("Uri")]
        public string Uri { get; set; }

        [JsonProperty("ImagePurpose")]
        public string ImagePurpose { get; set; }

        [JsonProperty("BackgroundColor")]
        public string BackgroundColor { get; set; }

        [JsonProperty("ForegroundColor")]
        public string ForegroundColor { get; set; }

        [JsonProperty("ImagePositionInfo")]
        public string ImagePositionInfo { get; set; }

        [JsonProperty("Height")]
        public int? Height { get; set; }

        [JsonProperty("Width")]
        public int? Width { get; set; }

        [JsonProperty("Caption")]
        public string Caption { get; set; }

        [JsonProperty("FileSizeInBytes")]
        public int? FileSizeInBytes { get; set; }

        [JsonProperty("UnscaledImageSHA256Hash")]
        public string UnscaledImageSHA256Hash { get; set; }

        [JsonProperty("CropSafeZone")]
        public object CropSafeZone { get; set; }
    }

}
