// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class InclusionProperty
    {

        [JsonProperty("OemId")]
        public string OemId { get; set; }

        [JsonProperty("MoId")]
        public string MoId { get; set; }

        [JsonProperty("ScmId")]
        public string ScmId { get; set; }
    }

}
