// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class LegalText
    {

        [JsonProperty("Tou")]
        public string Tou { get; set; }

        [JsonProperty("TouUri")]
        public string TouUri { get; set; }

        [JsonProperty("Copyright")]
        public string Copyright { get; set; }

        [JsonProperty("CopyrightUri")]
        public string CopyrightUri { get; set; }

        [JsonProperty("PrivacyPolicyUri")]
        public string PrivacyPolicyUri { get; set; }

        [JsonProperty("PrivacyPolicy")]
        public string PrivacyPolicy { get; set; }

        [JsonProperty("AdditionalLicenseTerms")]
        public string AdditionalLicenseTerms { get; set; }
    }

}
