// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class LocalizedProperty
    {

        [JsonProperty("DeveloperName")]
        public string DeveloperName { get; set; }

        [JsonProperty("PublisherName")]
        public string PublisherName { get; set; }

        [JsonProperty("PublisherWebsiteUri")]
        public string PublisherWebsiteUri { get; set; }

        [JsonProperty("SupportUri")]
        public string SupportUri { get; set; }

        [JsonProperty("DisplayPlatformProperties")]
        public IList<DisplayPlatformProperty> DisplayPlatformProperties { get; set; }

        [JsonProperty("SearchTitles")]
        public IList<SearchTitle> SearchTitles { get; set; }

        [JsonProperty("Images")]
        public IList<Image> Images { get; set; }

        [JsonProperty("SearchBoosts")]
        public IList<object> SearchBoosts { get; set; }

        [JsonProperty("ProductDescription")]
        public string ProductDescription { get; set; }

        [JsonProperty("ProductTitle")]
        public string ProductTitle { get; set; }

        [JsonProperty("Franchises")]
        public IList<object> Franchises { get; set; }

        [JsonProperty("Language")]
        public string Language { get; set; }

        [JsonProperty("Markets")]
        public IList<string> Markets { get; set; }

        [JsonProperty("Videos")]
        public IList<object> Videos { get; set; }

        [JsonProperty("EligibilityProperties")]
        public object EligibilityProperties { get; set; }

        [JsonProperty("ShortTitle")]
        public string ShortTitle { get; set; }

        [JsonProperty("SortTitle")]
        public string SortTitle { get; set; }

        [JsonProperty("ShortDescription")]
        public string ShortDescription { get; set; }

        [JsonProperty("VoiceTitle")]
        public string VoiceTitle { get; set; }

        [JsonProperty("ProductDisplayRanks")]
        public IList<object> ProductDisplayRanks { get; set; }
    }

}
