// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class LocalizedProperty2
    {

        [JsonProperty("PackageDetails")]
        public IList<object> PackageDetails { get; set; }

        [JsonProperty("LegalText")]
        public LegalText LegalText { get; set; }

        [JsonProperty("Contributors")]
        public IList<object> Contributors { get; set; }

        [JsonProperty("Images")]
        public IList<object> Images { get; set; }

        [JsonProperty("Features")]
        public IList<string> Features { get; set; }

        [JsonProperty("ReleaseNotes")]
        public string ReleaseNotes { get; set; }

        [JsonProperty("DisplayPlatformProperties")]
        public IList<object> DisplayPlatformProperties { get; set; }

        [JsonProperty("RecommendedHardware")]
        public string RecommendedHardware { get; set; }

        [JsonProperty("SkuDescription")]
        public string SkuDescription { get; set; }

        [JsonProperty("SkuTitle")]
        public string SkuTitle { get; set; }

        [JsonProperty("Language")]
        public string Language { get; set; }

        [JsonProperty("Markets")]
        public IList<string> Markets { get; set; }

        [JsonProperty("MinimumNotes")]
        public string MinimumNotes { get; set; }

        [JsonProperty("RecommendedNotes")]
        public string RecommendedNotes { get; set; }

        [JsonProperty("SkuButtonTitle")]
        public string SkuButtonTitle { get; set; }

        [JsonProperty("SkuDisplayRank")]
        public IList<object> SkuDisplayRank { get; set; }
    }

}
