// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class MarketProperty2
    {

        [JsonProperty("SupportedLanguages")]
        public IList<string> SupportedLanguages { get; set; }

        [JsonProperty("Markets")]
        public IList<string> Markets { get; set; }

        [JsonProperty("PIFilter")]
        public PIFilter PIFilter { get; set; }

        [JsonProperty("FirstAvailableDate")]
        public DateTime? FirstAvailableDate { get; set; }
    }

}
