// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class MarketProperty
    {

        [JsonProperty("OriginalReleaseDate")]
        public object OriginalReleaseDate { get; set; }

        [JsonProperty("OriginalReleaseDateFriendlyName")]
        public string OriginalReleaseDateFriendlyName { get; set; }

        [JsonProperty("UsageData")]
        public IList<UsageData> UsageData { get; set; }

        [JsonProperty("ContentRatings")]
        public IList<ContentRating> ContentRatings { get; set; }

        [JsonProperty("MinimumUserAge")]
        public int? MinimumUserAge { get; set; }

        [JsonProperty("RelatedProducts")]
        public IList<RelatedProduct> RelatedProducts { get; set; }

        [JsonProperty("Markets")]
        public IList<string> Markets { get; set; }
    }

}
