// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class OrderManagementData
    {

        [JsonProperty("AcceptablePIPolicy")]
        public string AcceptablePIPolicy { get; set; }

        [JsonProperty("Discounts")]
        public IList<object> Discounts { get; set; }

        [JsonProperty("Price")]
        public Price Price { get; set; }

        [JsonProperty("GracePeriodDurationInSeconds")]
        public int? GracePeriodDurationInSeconds { get; set; }

        [JsonProperty("GrantedEntitlementKeys")]
        public IList<string> GrantedEntitlementKeys { get; set; }

        [JsonProperty("PIFilter")]
        public PIFilter2 PIFilter { get; set; }
    }

}
