// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class Package
    {

        [JsonProperty("PackageId")]
        public string PackageId { get; set; }

        [JsonProperty("PackageFormat")]
        public string PackageFormat { get; set; }

        [JsonProperty("PackageUri")]
        public string PackageUri { get; set; }

        [JsonProperty("PackageFullName")]
        public string PackageFullName { get; set; }

        [JsonProperty("Architectures")]
        public IList<string> Architectures { get; set; }

        [JsonProperty("MaxDownloadSizeInBytes")]
        public long? MaxDownloadSizeInBytes { get; set; }

        [JsonProperty("PlatformDependencies")]
        public IList<PlatformDependency> PlatformDependencies { get; set; }

        [JsonProperty("FrameworkDependencies")]
        public IList<FrameworkDependency> FrameworkDependencies { get; set; }

        [JsonProperty("Capabilities")]
        public IList<string> Capabilities { get; set; }

        [JsonProperty("DeviceCapabilities")]
        public IList<string> DeviceCapabilities { get; set; }

        [JsonProperty("Languages")]
        public IList<string> Languages { get; set; }

        [JsonProperty("Applications")]
        public IList<Application> Applications { get; set; }

        [JsonProperty("HardwareRequirements")]
        public IList<string> HardwareRequirements { get; set; }

        [JsonProperty("IsStreamingApp")]
        public bool? IsStreamingApp { get; set; }

        [JsonProperty("ExperienceIds")]
        public IList<string> ExperienceIds { get; set; }

        [JsonProperty("HashAlgorithm")]
        public string HashAlgorithm { get; set; }

        [JsonProperty("Hash")]
        public string Hash { get; set; }

        [JsonProperty("PackageRank")]
        public int? PackageRank { get; set; }

        [JsonProperty("PlatformDependencyXmlBlob")]
        public string PlatformDependencyXmlBlob { get; set; }

        [JsonProperty("ResourceId")]
        public string ResourceId { get; set; }

        [JsonProperty("Version")]
        public string Version { get; set; }

        [JsonProperty("HardwareDependencies")]
        public IList<string> HardwareDependencies { get; set; }

        [JsonProperty("PackageFamilyName")]
        public string PackageFamilyName { get; set; }

        [JsonProperty("MaxInstallSizeInBytes")]
        public long? MaxInstallSizeInBytes { get; set; }

        [JsonProperty("ContentId")]
        public string ContentId { get; set; }

        [JsonProperty("KeyId")]
        public string KeyId { get; set; }

        [JsonProperty("PackageDownloadUris")]
        public IList<PackageDownloadUri> PackageDownloadUris { get; set; }
    }

}
