// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class PIFilter2
    {

        [JsonProperty("ExclusionProperties")]
        public IList<object> ExclusionProperties { get; set; }

        [JsonProperty("InclusionProperties")]
        public IList<object> InclusionProperties { get; set; }
    }

}
