// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class Price
    {

        [JsonProperty("ListPrice")]
        public double? ListPrice { get; set; }

        [JsonProperty("CurrencyCode")]
        public string CurrencyCode { get; set; }

        [JsonProperty("MSRP")]
        public double? MSRP { get; set; }

        [JsonProperty("WholesalePrice")]
        public double? WholesalePrice { get; set; }

        [JsonProperty("WholesaleCurrencyCode")]
        public string WholesaleCurrencyCode { get; set; }

        [JsonProperty("IsPIRequired")]
        public bool? IsPIRequired { get; set; }

        [JsonProperty("TaxType")]
        public string TaxType { get; set; }

        [JsonProperty("RecurrencePrice")]
        public object RecurrencePrice { get; set; }
    }

}
