// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class Product2
    {

        [JsonProperty("LastModifiedDate")]
        public object LastModifiedDate { get; set; }

        [JsonProperty("LocalizedProperties")]
        public IList<LocalizedProperty> LocalizedProperties { get; set; }

        [JsonProperty("MarketProperties")]
        public IList<MarketProperty> MarketProperties { get; set; }

        [JsonProperty("ProductASchema")]
        public string ProductASchema { get; set; }

        [JsonProperty("ProductBSchema")]
        public string ProductBSchema { get; set; }

        [JsonProperty("ProductId")]
        public string ProductId { get; set; }

        [JsonProperty("Properties")]
        public Properties Properties { get; set; }

        [JsonProperty("AlternateIds")]
        public IList<AlternateId> AlternateIds { get; set; }

        [JsonProperty("DomainDataVersion")]
        public string DomainDataVersion { get; set; }

        [JsonProperty("IngestionSource")]
        public string IngestionSource { get; set; }

        [JsonProperty("IsMicrosoftProduct")]
        public bool? IsMicrosoftProduct { get; set; }

        [JsonProperty("PreferredSkuId")]
        public string PreferredSkuId { get; set; }

        [JsonProperty("ProductType")]
        public string ProductType { get; set; }

        [JsonProperty("ValidationData")]
        public ValidationData ValidationData { get; set; }

        [JsonProperty("MerchandizingTags")]
        public IList<string> MerchandizingTags { get; set; }

        [JsonProperty("ProductFamily")]
        public string ProductFamily { get; set; }

        [JsonProperty("ProductKind")]
        public string ProductKind { get; set; }

        [JsonProperty("DisplaySkuAvailabilities")]
        public IList<DisplaySkuAvailability> DisplaySkuAvailabilities { get; set; }

        [JsonProperty("PartD")]
        public string PartD { get; set; }

        [JsonProperty("SchemaVersion")]
        public string SchemaVersion { get; set; }

        [JsonProperty("SandboxId")]
        public string SandboxId { get; set; }

        [JsonProperty("IsSandboxedProduct")]
        public bool? IsSandboxedProduct { get; set; }
    }

}
