// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class Properties2
    {

        [JsonProperty("LastUpdateDate")]
        public object LastUpdateDate { get; set; }

        [JsonProperty("VersionString")]
        public string VersionString { get; set; }

        [JsonProperty("Packages")]
        public IList<Package> Packages { get; set; }

        [JsonProperty("FulfillmentData")]
        public FulfillmentData FulfillmentData { get; set; }

        [JsonProperty("HasThirdPartyIAPs")]
        public bool? HasThirdPartyIAPs { get; set; }

        [JsonProperty("LegacyEntitlementKeys")]
        public IList<string> LegacyEntitlementKeys { get; set; }

        [JsonProperty("HardwareRequirements")]
        public IList<string> HardwareRequirements { get; set; }

        [JsonProperty("HardwareWarningList")]
        public IList<string> HardwareWarningList { get; set; }

        [JsonProperty("LicensingPolicyType")]
        public string LicensingPolicyType { get; set; }

        [JsonProperty("MagazineIssueReleaseFrequency")]
        public object MagazineIssueReleaseFrequency { get; set; }

        [JsonProperty("VisibleToB2BServiceIds")]
        public IList<string> VisibleToB2BServiceIds { get; set; }

        [JsonProperty("Delivery")]
        public Delivery Delivery { get; set; }

        [JsonProperty("FulfillmentType")]
        public string FulfillmentType { get; set; }

        [JsonProperty("InstallationTerms")]
        public object InstallationTerms { get; set; }

        [JsonProperty("SkuDisplayRank")]
        public int? SkuDisplayRank { get; set; }

        [JsonProperty("EarlyAdopterEnrollmentUrl")]
        public object EarlyAdopterEnrollmentUrl { get; set; }

        [JsonProperty("HardwareProperties")]
        public HardwareProperties HardwareProperties { get; set; }

        [JsonProperty("XboxXPA")]
        public bool? XboxXPA { get; set; }

        [JsonProperty("BundledSkus")]
        public IList<object> BundledSkus { get; set; }

        [JsonProperty("IsPreOrder")]
        public bool? IsPreOrder { get; set; }

        [JsonProperty("IsRepurchasable")]
        public bool? IsRepurchasable { get; set; }

        [JsonProperty("AdditionalIdentifiers")]
        public IList<object> AdditionalIdentifiers { get; set; }

        [JsonProperty("IsTrial")]
        public bool? IsTrial { get; set; }

        [JsonProperty("IsBundle")]
        public bool? IsBundle { get; set; }

        [JsonProperty("SkuDisplayGroupIds")]
        public IList<string> SkuDisplayGroupIds { get; set; }

        [JsonProperty("TrialTimeInSeconds")]
        public int? TrialTimeInSeconds { get; set; }

        [JsonProperty("DisplayRank")]
        public IList<object> DisplayRank { get; set; }
    }

}
