// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class Properties3
    {

        [JsonProperty("ExactTitleSearch")]
        public bool? ExactTitleSearch { get; set; }

        [JsonProperty("OriginalReleaseDate")]
        public DateTime? OriginalReleaseDate { get; set; }
    }

}
