// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class Properties
    {

        [JsonProperty("IsSettingsApp")]
        public bool? IsSettingsApp { get; set; }

        [JsonProperty("IsAccessible")]
        public bool? IsAccessible { get; set; }

        [JsonProperty("PackageIdentityName")]
        public string PackageIdentityName { get; set; }

        [JsonProperty("PackageFamilyName")]
        public string PackageFamilyName { get; set; }

        [JsonProperty("PublisherCertificateName")]
        public string PublisherCertificateName { get; set; }

        [JsonProperty("PublisherId")]
        public string PublisherId { get; set; }

        [JsonProperty("PrimaryCategory")]
        public string PrimaryCategory { get; set; }

        [JsonProperty("Category")]
        public string Category { get; set; }

        [JsonProperty("Subcategory")]
        public string Subcategory { get; set; }

        [JsonProperty("IsLineOfBusinessApp")]
        public bool? IsLineOfBusinessApp { get; set; }

        [JsonProperty("BlockedDevices")]
        public IList<object> BlockedDevices { get; set; }

        [JsonProperty("HasAddOns")]
        public bool? HasAddOns { get; set; }

        [JsonProperty("IsPublishedToLegacyWindowsPhoneStore")]
        public bool? IsPublishedToLegacyWindowsPhoneStore { get; set; }

        [JsonProperty("IsPublishedToLegacyWindowsStore")]
        public bool? IsPublishedToLegacyWindowsStore { get; set; }

        [JsonProperty("CanInstallToSDCard")]
        public bool? CanInstallToSDCard { get; set; }

        [JsonProperty("DiscoveryExclusivityProperties")]
        public DiscoveryExclusivityProperties DiscoveryExclusivityProperties { get; set; }

        [JsonProperty("Attributes")]
        public IList<Attribute> Attributes { get; set; }

        [JsonProperty("SubCategory")]
        public string SubCategory { get; set; }

        [JsonProperty("Categories")]
        public IList<string> Categories { get; set; }

        [JsonProperty("XboxXPA")]
        public object XboxXPA { get; set; }

        [JsonProperty("PdpBackgroundColor")]
        public string PdpBackgroundColor { get; set; }

        [JsonProperty("IsDemo")]
        public bool? IsDemo { get; set; }

        [JsonProperty("SkuDisplayGroups")]
        public IList<SkuDisplayGroup> SkuDisplayGroups { get; set; }

        [JsonProperty("EntitlementProperties")]
        public IList<string> EntitlementProperties { get; set; }
    }

}
