// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class Remediation
    {

        [JsonProperty("RemediationId")]
        public string RemediationId { get; set; }

        [JsonProperty("Type")]
        public string Type { get; set; }
    }

}
