// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class Sku
    {

        [JsonProperty("LastModifiedDate")]
        public DateTime? LastModifiedDate { get; set; }

        [JsonProperty("LocalizedProperties")]
        public IList<LocalizedProperty2> LocalizedProperties { get; set; }

        [JsonProperty("MarketProperties")]
        public IList<MarketProperty2> MarketProperties { get; set; }

        [JsonProperty("ProductId")]
        public string ProductId { get; set; }

        [JsonProperty("Properties")]
        public Properties2 Properties { get; set; }

        [JsonProperty("SkuASchema")]
        public string SkuASchema { get; set; }

        [JsonProperty("SkuBSchema")]
        public string SkuBSchema { get; set; }

        [JsonProperty("SkuId")]
        public string SkuId { get; set; }

        [JsonProperty("SkuType")]
        public string SkuType { get; set; }

        [JsonProperty("RecurrencePolicy")]
        public object RecurrencePolicy { get; set; }

        [JsonProperty("SubscriptionPolicyId")]
        public object SubscriptionPolicyId { get; set; }
    }

}
