// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class UsageData
    {

        [JsonProperty("AggregateTimeSpan")]
        public string AggregateTimeSpan { get; set; }

        [JsonProperty("PlayCount")]
        public double? PlayCount { get; set; }

        [JsonProperty("PurchaseCount")]
        public double? PurchaseCount { get; set; }

        [JsonProperty("RatingCount")]
        public double? RatingCount { get; set; }

        [JsonProperty("AverageRating")]
        public double? AverageRating { get; set; }

        [JsonProperty("RentalCount")]
        public double? RentalCount { get; set; }

        [JsonProperty("TrialCount")]
        public double? TrialCount { get; set; }
    }

}
