// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using DCATLib.ObjectClasses.Product;

namespace DCATLib.ObjectClasses.Product
{

    public class ValidationData
    {

        [JsonProperty("PassedValidation")]
        public bool? PassedValidation { get; set; }

        [JsonProperty("RevisionId")]
        public string RevisionId { get; set; }

        [JsonProperty("ValidationResultUri")]
        public string ValidationResultUri { get; set; }
    }

}
